export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body>
      <header><h1 style={{backgroundColor:"skyblue"}}>Header</h1></header>
        {children}
        <footer><h2 style={{
        backgroundColor:"ghostwhite"
      }}>Footer</h2></footer></body>
      
    </html>
  )
}
